export const ADD_STAFFS = 'ADD_STAFFS';
export const STAFFS_LOADING = 'STAFFS_LOADING';
export const STAFFS_FAILED = 'STAFFS_FAILED';
export const ADD_DEPARTMENT = 'ADD_DEPARTMENT';
export const DEPARTMENT_LOADING = 'DEPARTMENT_LOADING';
export const DEPARTMENT_FAILED = 'DEPARTMENT_FAILED';
export const ADD_NEWSTAFF = 'ADD_NEWSTAFF';
export const UPDATE_STAFF = 'UPDATE_NEWSTAFF';